# Generated by Django 5.2.5 on 2025-08-12 16:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_titre', models.CharField(help_text='Numéro unique du titre', max_length=100, unique=True)),
                ('type', models.CharField(choices=[('licence_type_1', 'Licence de type 1'), ('licence_type_2', 'Licence de type 2'), ('agrement_vendeurs', 'Agrément vendeurs'), ('agrement_installateurs', 'Agrément installateurs'), ('concessions', 'Concessions'), ('recepisse', 'Récépissé')], max_length=50)),
                ('entreprise_nom', models.CharField(help_text="Nom de l'entreprise propriétaire", max_length=255)),
                ('date_emission', models.DateField(help_text="Date d'émission du titre")),
                ('date_expiration', models.DateField(help_text="Date d'expiration du titre")),
                ('duree_ans', models.PositiveIntegerField(help_text='Durée en années', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('expire', 'Expiré')], default='en_attente', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description du titre', null=True)),
                ('conditions_specifiques', models.JSONField(default=list, help_text='Conditions spécifiques du titre')),
                ('redevance_annuelle', models.DecimalField(decimal_places=2, default=0.0, help_text='Redevance annuelle en FCFA', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Titre',
                'verbose_name_plural': 'Titres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedevanceTitre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee', models.PositiveIntegerField(help_text='Année de la redevance')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant de la redevance', max_digits=12)),
                ('date_echeance', models.DateField(help_text="Date d'échéance du paiement")),
                ('date_paiement', models.DateField(blank=True, help_text='Date effective du paiement', null=True)),
                ('status_paiement', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('en_retard', 'En retard'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('reference_paiement', models.CharField(blank=True, help_text='Référence du paiement', max_length=100, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redevances', to='titres.titre')),
            ],
            options={
                'verbose_name': 'Redevance Titre',
                'verbose_name_plural': 'Redevances Titres',
                'ordering': ['-annee', '-date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueTitre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('renouvellement', 'Renouvellement'), ('suspension', 'Suspension'), ('reactivation', 'Réactivation'), ('expiration', 'Expiration')], max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('ancien_status', models.CharField(blank=True, max_length=20, null=True)),
                ('nouveau_status', models.CharField(blank=True, max_length=20, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('donnees_modifiees', models.JSONField(default=dict, help_text='Données qui ont été modifiées')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='titres.titre')),
            ],
            options={
                'verbose_name': 'Historique Titre',
                'verbose_name_plural': 'Historiques Titres',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddIndex(
            model_name='titre',
            index=models.Index(fields=['numero_titre'], name='titres_titr_numero__083671_idx'),
        ),
        migrations.AddIndex(
            model_name='titre',
            index=models.Index(fields=['type'], name='titres_titr_type_680de9_idx'),
        ),
        migrations.AddIndex(
            model_name='titre',
            index=models.Index(fields=['status'], name='titres_titr_status_3a5892_idx'),
        ),
        migrations.AddIndex(
            model_name='titre',
            index=models.Index(fields=['date_expiration'], name='titres_titr_date_ex_06d5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='titre',
            index=models.Index(fields=['proprietaire'], name='titres_titr_proprie_fd0771_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='redevancetitre',
            unique_together={('titre', 'annee')},
        ),
    ]
