# Generated by Django 5.2.5 on 2025-08-14 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la sauvegarde')),
                ('backup_type', models.CharField(choices=[('full', 'Complète'), ('incremental', 'Incrémentale'), ('data_only', 'Données seules'), ('config_only', 'Configuration seule')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin du fichier')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Taille (bytes)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sauvegarde Système',
                'verbose_name_plural': 'Sauvegardes Système',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clé de configuration')),
                ('value', models.TextField(verbose_name='Valeur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(default='general', max_length=50, verbose_name='Catégorie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration Système',
                'verbose_name_plural': 'Configurations Système',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SystemMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=10)),
                ('scheduled_start', models.DateTimeField(verbose_name='Début planifié')),
                ('scheduled_end', models.DateTimeField(verbose_name='Fin planifiée')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Début réel')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin réelle')),
                ('impact_description', models.TextField(blank=True, verbose_name="Description de l'impact")),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notification envoyée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Système',
                'verbose_name_plural': 'Maintenances Système',
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('users_active', 'Utilisateurs actifs'), ('requests_count', 'Nombre de requêtes'), ('response_time', 'Temps de réponse (ms)'), ('error_rate', "Taux d'erreur (%)"), ('database_size', 'Taille base de données (MB)'), ('storage_used', 'Stockage utilisé (MB)'), ('memory_usage', 'Utilisation mémoire (%)'), ('cpu_usage', 'Utilisation CPU (%)')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Métrique Système',
                'verbose_name_plural': 'Métriques Système',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', '-timestamp'], name='system_admi_metric__376881_idx'), models.Index(fields=['-timestamp'], name='system_admi_timesta_8c8bae_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('export', 'Export'), ('import', 'Import'), ('config', 'Configuration'), ('backup', 'Sauvegarde'), ('restore', 'Restauration')], max_length=20)),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], default='info', max_length=10)),
                ('resource_type', models.CharField(max_length=50, verbose_name='Type de ressource')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='ID de ressource')),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'Audit",
                'verbose_name_plural': "Journaux d'Audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='system_admi_user_id_9c4071_idx'), models.Index(fields=['action', '-timestamp'], name='system_admi_action_7182a1_idx'), models.Index(fields=['level', '-timestamp'], name='system_admi_level_80f87c_idx'), models.Index(fields=['resource_type', '-timestamp'], name='system_admi_resourc_ed5299_idx')],
            },
        ),
    ]
